export interface Country {
  name: string;
  dialCode: string;
  maxPhoneDigits?: number;
}

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", dialCode: "+93", maxPhoneDigits: 9 },
  { name: "Albania", dialCode: "+355", maxPhoneDigits: 9 },
  { name: "Algeria", dialCode: "+213", maxPhoneDigits: 9 },
  { name: "Andorra", dialCode: "+376", maxPhoneDigits: 9 },
  { name: "Angola", dialCode: "+244", maxPhoneDigits: 9 },
  { name: "Argentina", dialCode: "+54", maxPhoneDigits: 10 },
  { name: "Armenia", dialCode: "+374", maxPhoneDigits: 8 },
  { name: "Australia", dialCode: "+61", maxPhoneDigits: 10 },
  { name: "Austria", dialCode: "+43", maxPhoneDigits: 11 },
  { name: "Azerbaijan", dialCode: "+994", maxPhoneDigits: 9 },
  { name: "Bahamas", dialCode: "+1-242", maxPhoneDigits: 10 },
  { name: "Bahrain", dialCode: "+973", maxPhoneDigits: 8 },
  { name: "Bangladesh", dialCode: "+880", maxPhoneDigits: 11 },
  { name: "Belarus", dialCode: "+375", maxPhoneDigits: 9 },
  { name: "Belgium", dialCode: "+32", maxPhoneDigits: 9 },
  { name: "Belize", dialCode: "+501", maxPhoneDigits: 7 },
  { name: "Benin", dialCode: "+229", maxPhoneDigits: 8 },
  { name: "Bhutan", dialCode: "+975", maxPhoneDigits: 8 },
  { name: "Bolivia", dialCode: "+591", maxPhoneDigits: 8 },
  { name: "Bosnia and Herzegovina", dialCode: "+387", maxPhoneDigits: 8 },
  { name: "Botswana", dialCode: "+267", maxPhoneDigits: 8 },
  { name: "Brazil", dialCode: "+55", maxPhoneDigits: 11 },
  { name: "Brunei", dialCode: "+673", maxPhoneDigits: 7 },
  { name: "Bulgaria", dialCode: "+359", maxPhoneDigits: 9 },
  { name: "Burkina Faso", dialCode: "+226", maxPhoneDigits: 8 },
  { name: "Burundi", dialCode: "+257", maxPhoneDigits: 8 },
  { name: "Cambodia", dialCode: "+855", maxPhoneDigits: 9 },
  { name: "Cameroon", dialCode: "+237", maxPhoneDigits: 9 },
  { name: "Canada", dialCode: "+1", maxPhoneDigits: 10 },
  { name: "Cape Verde", dialCode: "+238", maxPhoneDigits: 7 },
  { name: "Central African Republic", dialCode: "+236", maxPhoneDigits: 8 },
  { name: "Chad", dialCode: "+235", maxPhoneDigits: 8 },
  { name: "Chile", dialCode: "+56", maxPhoneDigits: 9 },
  { name: "China", dialCode: "+86", maxPhoneDigits: 11 },
  { name: "Colombia", dialCode: "+57", maxPhoneDigits: 10 },
  { name: "Comoros", dialCode: "+269", maxPhoneDigits: 7 },
  { name: "Congo", dialCode: "+242", maxPhoneDigits: 9 },
  { name: "Costa Rica", dialCode: "+506", maxPhoneDigits: 8 },
  { name: "Croatia", dialCode: "+385", maxPhoneDigits: 9 },
  { name: "Cuba", dialCode: "+53", maxPhoneDigits: 8 },
  { name: "Cyprus", dialCode: "+357", maxPhoneDigits: 8 },
  { name: "Czech Republic", dialCode: "+420", maxPhoneDigits: 9 },
  { name: "Denmark", dialCode: "+45", maxPhoneDigits: 8 },
  { name: "Djibouti", dialCode: "+253", maxPhoneDigits: 8 },
  { name: "Dominican Republic", dialCode: "+1-809", maxPhoneDigits: 10 },
  { name: "DR Congo", dialCode: "+243", maxPhoneDigits: 9 },
  { name: "Ecuador", dialCode: "+593", maxPhoneDigits: 9 },
  { name: "Egypt", dialCode: "+20", maxPhoneDigits: 10 },
  { name: "El Salvador", dialCode: "+503", maxPhoneDigits: 8 },
  { name: "Equatorial Guinea", dialCode: "+240", maxPhoneDigits: 9 },
  { name: "Eritrea", dialCode: "+291", maxPhoneDigits: 7 },
  { name: "Estonia", dialCode: "+372", maxPhoneDigits: 8 },
  { name: "Eswatini", dialCode: "+268", maxPhoneDigits: 8 },
  { name: "Ethiopia", dialCode: "+251", maxPhoneDigits: 9 },
  { name: "Fiji", dialCode: "+679", maxPhoneDigits: 7 },
  { name: "Finland", dialCode: "+358", maxPhoneDigits: 10 },
  { name: "France", dialCode: "+33", maxPhoneDigits: 9 },
  { name: "Gabon", dialCode: "+241", maxPhoneDigits: 8 },
  { name: "Gambia", dialCode: "+220", maxPhoneDigits: 7 },
  { name: "Georgia", dialCode: "+995", maxPhoneDigits: 9 },
  { name: "Germany", dialCode: "+49", maxPhoneDigits: 11 },
  { name: "Ghana", dialCode: "+233", maxPhoneDigits: 9 },
  { name: "Greece", dialCode: "+30", maxPhoneDigits: 10 },
  { name: "Guatemala", dialCode: "+502", maxPhoneDigits: 8 },
  { name: "Guinea", dialCode: "+224", maxPhoneDigits: 9 },
  { name: "Guinea-Bissau", dialCode: "+245", maxPhoneDigits: 7 },
  { name: "Guyana", dialCode: "+592", maxPhoneDigits: 7 },
  { name: "Haiti", dialCode: "+509", maxPhoneDigits: 8 },
  { name: "Honduras", dialCode: "+504", maxPhoneDigits: 8 },
  { name: "Hungary", dialCode: "+36", maxPhoneDigits: 9 },
  { name: "Iceland", dialCode: "+354", maxPhoneDigits: 7 },
  { name: "India", dialCode: "+91", maxPhoneDigits: 10 },
  { name: "Indonesia", dialCode: "+62", maxPhoneDigits: 12 },
  { name: "Iran", dialCode: "+98", maxPhoneDigits: 10 },
  { name: "Iraq", dialCode: "+964", maxPhoneDigits: 10 },
  { name: "Ireland", dialCode: "+353", maxPhoneDigits: 9 },
  { name: "Israel", dialCode: "+972", maxPhoneDigits: 9 },
  { name: "Italy", dialCode: "+39", maxPhoneDigits: 10 },
  { name: "Ivory Coast", dialCode: "+225", maxPhoneDigits: 10 },
  { name: "Jamaica", dialCode: "+1-876", maxPhoneDigits: 10 },
  { name: "Japan", dialCode: "+81", maxPhoneDigits: 11 },
  { name: "Jordan", dialCode: "+962", maxPhoneDigits: 9 },
  { name: "Kazakhstan", dialCode: "+7", maxPhoneDigits: 10 },
  { name: "Kenya", dialCode: "+254", maxPhoneDigits: 9 },
  { name: "Kuwait", dialCode: "+965", maxPhoneDigits: 8 },
  { name: "Kyrgyzstan", dialCode: "+996", maxPhoneDigits: 9 },
  { name: "Laos", dialCode: "+856", maxPhoneDigits: 9 },
  { name: "Latvia", dialCode: "+371", maxPhoneDigits: 8 },
  { name: "Lebanon", dialCode: "+961", maxPhoneDigits: 8 },
  { name: "Lesotho", dialCode: "+266", maxPhoneDigits: 8 },
  { name: "Liberia", dialCode: "+231", maxPhoneDigits: 8 },
  { name: "Libya", dialCode: "+218", maxPhoneDigits: 9 },
  { name: "Liechtenstein", dialCode: "+423", maxPhoneDigits: 9 },
  { name: "Lithuania", dialCode: "+370", maxPhoneDigits: 8 },
  { name: "Luxembourg", dialCode: "+352", maxPhoneDigits: 9 },
  { name: "Madagascar", dialCode: "+261", maxPhoneDigits: 9 },
  { name: "Malawi", dialCode: "+265", maxPhoneDigits: 9 },
  { name: "Malaysia", dialCode: "+60", maxPhoneDigits: 11 },
  { name: "Maldives", dialCode: "+960", maxPhoneDigits: 7 },
  { name: "Mali", dialCode: "+223", maxPhoneDigits: 8 },
  { name: "Malta", dialCode: "+356", maxPhoneDigits: 8 },
  { name: "Mauritania", dialCode: "+222", maxPhoneDigits: 8 },
  { name: "Mauritius", dialCode: "+230", maxPhoneDigits: 8 },
  { name: "Mexico", dialCode: "+52", maxPhoneDigits: 10 },
  { name: "Moldova", dialCode: "+373", maxPhoneDigits: 8 },
  { name: "Monaco", dialCode: "+377", maxPhoneDigits: 9 },
  { name: "Mongolia", dialCode: "+976", maxPhoneDigits: 8 },
  { name: "Montenegro", dialCode: "+382", maxPhoneDigits: 8 },
  { name: "Morocco", dialCode: "+212", maxPhoneDigits: 9 },
  { name: "Mozambique", dialCode: "+258", maxPhoneDigits: 9 },
  { name: "Myanmar", dialCode: "+95", maxPhoneDigits: 10 },
  { name: "Namibia", dialCode: "+264", maxPhoneDigits: 9 },
  { name: "Nepal", dialCode: "+977", maxPhoneDigits: 10 },
  { name: "Netherlands", dialCode: "+31", maxPhoneDigits: 9 },
  { name: "New Zealand", dialCode: "+64", maxPhoneDigits: 9 },
  { name: "Nicaragua", dialCode: "+505", maxPhoneDigits: 8 },
  { name: "Niger", dialCode: "+227", maxPhoneDigits: 8 },
  { name: "Nigeria", dialCode: "+234", maxPhoneDigits: 10 },
  { name: "North Korea", dialCode: "+850", maxPhoneDigits: 10 },
  { name: "North Macedonia", dialCode: "+389", maxPhoneDigits: 8 },
  { name: "Norway", dialCode: "+47", maxPhoneDigits: 8 },
  { name: "Oman", dialCode: "+968", maxPhoneDigits: 8 },
  { name: "Pakistan", dialCode: "+92", maxPhoneDigits: 10 },
  { name: "Palestine", dialCode: "+970", maxPhoneDigits: 9 },
  { name: "Panama", dialCode: "+507", maxPhoneDigits: 8 },
  { name: "Papua New Guinea", dialCode: "+675", maxPhoneDigits: 8 },
  { name: "Paraguay", dialCode: "+595", maxPhoneDigits: 9 },
  { name: "Peru", dialCode: "+51", maxPhoneDigits: 9 },
  { name: "Philippines", dialCode: "+63", maxPhoneDigits: 10 },
  { name: "Poland", dialCode: "+48", maxPhoneDigits: 9 },
  { name: "Portugal", dialCode: "+351", maxPhoneDigits: 9 },
  { name: "Qatar", dialCode: "+974", maxPhoneDigits: 8 },
  { name: "Romania", dialCode: "+40", maxPhoneDigits: 9 },
  { name: "Russia", dialCode: "+7", maxPhoneDigits: 10 },
  { name: "Rwanda", dialCode: "+250", maxPhoneDigits: 9 },
  { name: "Saudi Arabia", dialCode: "+966", maxPhoneDigits: 9 },
  { name: "Senegal", dialCode: "+221", maxPhoneDigits: 9 },
  { name: "Serbia", dialCode: "+381", maxPhoneDigits: 9 },
  { name: "Sierra Leone", dialCode: "+232", maxPhoneDigits: 8 },
  { name: "Singapore", dialCode: "+65", maxPhoneDigits: 8 },
  { name: "Slovakia", dialCode: "+421", maxPhoneDigits: 9 },
  { name: "Slovenia", dialCode: "+386", maxPhoneDigits: 8 },
  { name: "Somalia", dialCode: "+252", maxPhoneDigits: 8 },
  { name: "South Africa", dialCode: "+27", maxPhoneDigits: 9 },
  { name: "South Korea", dialCode: "+82", maxPhoneDigits: 11 },
  { name: "South Sudan", dialCode: "+211", maxPhoneDigits: 9 },
  { name: "Spain", dialCode: "+34", maxPhoneDigits: 9 },
  { name: "Sri Lanka", dialCode: "+94", maxPhoneDigits: 9 },
  { name: "Sudan", dialCode: "+249", maxPhoneDigits: 9 },
  { name: "Suriname", dialCode: "+597", maxPhoneDigits: 7 },
  { name: "Sweden", dialCode: "+46", maxPhoneDigits: 9 },
  { name: "Switzerland", dialCode: "+41", maxPhoneDigits: 9 },
  { name: "Syria", dialCode: "+963", maxPhoneDigits: 9 },
  { name: "Taiwan", dialCode: "+886", maxPhoneDigits: 9 },
  { name: "Tajikistan", dialCode: "+992", maxPhoneDigits: 9 },
  { name: "Tanzania", dialCode: "+255", maxPhoneDigits: 9 },
  { name: "Thailand", dialCode: "+66", maxPhoneDigits: 9 },
  { name: "Timor-Leste", dialCode: "+670", maxPhoneDigits: 8 },
  { name: "Togo", dialCode: "+228", maxPhoneDigits: 8 },
  { name: "Trinidad and Tobago", dialCode: "+1-868", maxPhoneDigits: 10 },
  { name: "Tunisia", dialCode: "+216", maxPhoneDigits: 8 },
  { name: "Turkey", dialCode: "+90", maxPhoneDigits: 10 },
  { name: "Turkmenistan", dialCode: "+993", maxPhoneDigits: 8 },
  { name: "Uganda", dialCode: "+256", maxPhoneDigits: 9 },
  { name: "Ukraine", dialCode: "+380", maxPhoneDigits: 9 },
  { name: "UAE", dialCode: "+971", maxPhoneDigits: 9 },
  { name: "United Kingdom", dialCode: "+44", maxPhoneDigits: 11 },
  { name: "United States", dialCode: "+1", maxPhoneDigits: 10 },
  { name: "Uruguay", dialCode: "+598", maxPhoneDigits: 9 },
  { name: "Uzbekistan", dialCode: "+998", maxPhoneDigits: 9 },
  { name: "Venezuela", dialCode: "+58", maxPhoneDigits: 10 },
  { name: "Vietnam", dialCode: "+84", maxPhoneDigits: 10 },
  { name: "Yemen", dialCode: "+967", maxPhoneDigits: 9 },
  { name: "Zambia", dialCode: "+260", maxPhoneDigits: 9 },
  { name: "Zimbabwe", dialCode: "+263", maxPhoneDigits: 9 },
];
